import Navbar from '@/components/navbar'
import '@/app/globals.css'
import type { Metadata } from 'next'
import ToasterProvider from '@/providers/toaster-provider'
import SignalRProvider from '@/providers/signalr-provider'
import { getCurrentUser } from '@/actions/auth/getCurrentUser'

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentUser()
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <Navbar />
        <main className="container px-2 pt-10 pb-4 mx-auto">
          <SignalRProvider user={user}>{children}</SignalRProvider>
        </main>
      </body>
    </html>
  )
}
