import Navbar from '@/components/navbar'
import '@/app/globals.css'
import type { Metadata } from 'next'
import ToasterProvider from '@/providers/toaster-provider'

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <Navbar />
        <main className="container px-2 pt-10 pb-4 mx-auto">{children}</main>
      </body>
    </html>
  )
}
